### PR TITLE
number of tasks shown printout has been corrected

### PR DESCRIPTION
**Pull request by chrisbeardy**

### CODE REVIEW

**Comment by klausweiss** [comment]
Hi. Thanks for the input! 

I will happily help you with the issue. I think we could leverage the `TODOTXT_FINAL_FILTER` option of `todo.sh` and instead of processing the whole `ls` command output, process only todo entries, leaving the rest of the work to `todo.sh`.

For task as simple as filtering using python is too much. This all can be achieved with just `grep` (shoutout to @bozakov's  https://github.com/bozakov/todo.txt-hide).

I will be glad to accept the PR if you use `TODOTXT_FINAL_FILTER` env var and ditch the python script to achieve that.

**Comment by chrisbeardy** [comment]
Hi, sorry I am confisued by your response. The purpose of my PR is to correct the print out of number of tasks shown when using the addon. This addon already uses python to do the filtering of the ```ls``` command, this is not something I added.

The issue I am trying to correct is that when when using the addon. As it takes the raw output of ```ls``` it will print at the end : ```65 of 65 tasks shown``` for example. However as we are using the hiding add-on this info is not correct.  

Interestingly todo.txt-hide also suffers from the same issue.

**Comment by chrisbeardy** [comment]
To clarify using ```todo.sh ls``` prints a line at the end saying how many tasks are shown, e.g:

```
todo.sh ls +todo
...
45 of 65 tasks shown
```

However with this addon, it always states that all tasks are shown but this would not be correct if we are hiding something. 

Current representative output:

```
todo.sh ls

task 1 +todo
task 2 +todo
task 3 +other

3 of 3 tasks shown

todo.sh hiding +todo

task 3 +other

3 of 3 tasks shown
```

Output should be:

```
todo.sh ls

task 1 +todo
task 2 +todo
task 3 +other

3 of 3 tasks shown

todo.sh hiding +todo

task 3 +other

1 of 3 tasks shown
```

My PR merely meant to correct this behaviour, not change the core addon.

**Comment by klausweiss** [comment]
> My PR merely meant to correct this behaviour, not change the core addon.

I understand. It's an opportunity to improve the plugin on a whole different level ;)

We can ditch python from the plugin and use a mechanism which todo.sh authors intended to be used for filtering. Thanks to that there will be no functionality duplication with the base application (counting shown tasks, displaying that info).

Let me know if you want to implement that. If not, I'll spend some time on it.

**Comment by chrisbeardy** [comment]
Ah I see. Yes I agree, reprinting the output of todo isn't as efficient as using Todo itself to do the filtering. But using python is certainly effective ha. So it would be nice to have it as a complete bash script. I'm happy for you to take a look at this.

**Comment by klausweiss** [comment]
Implemented. Closing.

**Pull request closed without merging**
